### PR TITLE
refactored googlechat action

### PR DESCRIPTION
**Pull request by dannyb1983**
# Refactored Google Chat

## Files changed

- actions/SendGoogleChat/templates/aws-event.yml
-  actions/SendGoogleChat/index.js 
-  actions/SendDiscord/index.js 
- actions.yml

## Bug fixes
- Fixed issue with extra blank messages appearing in google chat window
- Fixed issue with the header messages not being displayed in google chat for certain events (like root login)
- Reformatted the google chat messages so all of the event details are contained in one "section"
- Added time elapsed information to the googleChat aws template
- fixed a typo in actions/sendDiscord/index.js

## Other Changes
- Changed times in the actions.yml to 10 seconds
- Added an "Instance terminated" message after the remediation step of `UnauthorizedInstanceCreated`  in actions.yml

### CODE REVIEW

**Review by keinu — APPROVED** [review]
Amazing! Thank you @dannyb1983, great work!

**Comment by keinu** [comment]
@Rahmteen would you mind taking a look at it?

**Comment by Rahmteen** [comment]
> @Rahmteen would you mind taking a look at it?

Power outages where I'm at currently- will take a look tonight !

**Comment by keinu** [comment]
> > @Rahmteen would you mind taking a look at it?
> 
> Power outages where I'm at currently- will take a look tonight !

Sorry to hear that, no rush at all

**Pull request merged**
